### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by wiggin77** [hisashi32/hxgzip#1]
There seems to be a bug in the API.  I can't get it to work.

**Comment by hisashi32** [comment]
I learned from the best. I'm not going to take this from a carpenter in training.

**Comment by wiggin77** [comment]
I can't figure out how to get my router to forward packets.  

![router](https://user-images.githubusercontent.com/5024605/36401339-edbd7d2e-15a4-11e8-94ad-b5b51c9e3b39.jpg)
